#pragma once

#include <stdexcept>
#include <string>
#include <system_error>

/**
 * Base exception for the entire Radio project.
 * Catching this will catch any error generated by our code.
 */
class RadioError : public std::runtime_error {
public:
    using std::runtime_error::runtime_error;
};

/**
 * Errors related to the ICY/HTTP protocol parsing.
 */
class ProtocolError : public RadioError {
public:
    using RadioError::RadioError;
};

/**
 * Errors specifically for HTTP status codes (e.g., 404, 403).
 */
class HttpException : public ProtocolError {
public:
    int status_code;
    HttpException(int code, const std::string& message) 
        : ProtocolError(message), status_code(code) {}
};

/**
 * Errors involving the system/network layer (wraps errno / system errors).
 * This covers low-level system failures (e.g., socket creation failed).
 */
class NetworkError : public std::system_error {
public:
    NetworkError(int ev, const std::string& msg)
        : std::system_error(ev, std::generic_category(), msg) {}
};

/**
 * Errors for invalid command-line arguments.
 */
class ArgumentError : public RadioError {
public:
    using RadioError::RadioError;
};

/**
 * Base class for connection-related issues.
 */
class ConnectionException : public RadioError {
public:
    using RadioError::RadioError;
};

/**
 * Specifically thrown when the server unexpectedly drops the connection.
 */
class ServerDisconnectedException : public ConnectionException {
public:
    ServerDisconnectedException() : ConnectionException("Server closed the connection") {}
};

/**
 * Catch-all exception for malformed usage (e.g., improper URL, bad message type).
 * Classifying them under one unified exception keeps the hierarchy clean.
 */
class InvalidRequestException : public RadioError {
public:
    using RadioError::RadioError;
};